version: '3'
services:
  api-dev:
    build: 
      context: app
      dockerfile: Dockerfile
    ports:
      - 8081:5000
    environment:
      DATABASE_HOST: db-dev
      DATABASE_NAME: db-dev
      DATABASE_USER: admin
      DATABASE_PASSWORD: db4dev$
    depends_on:
      - db-dev

  api-test:
    build: 
      context: app
      dockerfile: Dockerfile
    ports:
      - 8082:5000
    environment:
      DATABASE_HOST: db-test
      DATABASE_NAME: db-test
      DATABASE_USER: admin
      DATABASE_PASSWORD: db4test$
    depends_on:
      - db-test

  db-dev:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: db4dev$
    volumes:
      - db_data_dev:/var/lib/mysql

  myadmin-dev:
    image: phpmyadmin
    environment:
      PMA_HOST: db-dev
    ports:
      - 9084:80
    depends_on:
      - db-dev

  db-test:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-test
      MYSQL_USER: admin
      MYSQL_PASSWORD: db4test$
    volumes:
      - db_data_test:/var/lib/mysql

  myadmin-test:
    image: phpmyadmin
    environment:
      PMA_HOST: db-test
    ports:
      - 9085:80
    depends_on:
      - db-test

volumes:
  db_data_dev:
  db_data_test:
